'use server';

import { getCurrentUser } from '@/lib/auth/get-user';
import { assertBalanceOrLog } from '@/server/lib/assert-balance-or-log';
import { assertCapabilityOrLog } from '@/server/lib/assert-capability-or-log';
import { getAccountTier } from '@/server/lib/get-account-tier';
import { getBalance } from '@/server/lib/get-balance';
import { getMediaProvider } from '@/server/lib/media-provider-factory';
import { reserveMediaJob } from '@/server/lib/rate-limit';
import {
  finalizeMediaJobReservation,
  recordPendingJob,
  rollbackMediaJobReservation,
} from '@/server/lib/scene-helpers';
import {
  BalanceGateError,
  type ModelTier,
  type StoredAsset,
  TierGateError,
  getVideoModelMeta,
  priceKopeks,
} from '@mango/core';
import { getServerSupabase } from '@mango/db/server';
import { z } from 'zod';

const InputSchema = z.object({
  project_id: z.string().uuid(),
});

type Input = z.infer<typeof InputSchema>;

type FinalClip = {
  storage: StoredAsset;
  composed_from: {
    video_version_id: string;
    voice_audio_version_id: string | null;
  };
};

type SceneAssetVersion = {
  version_id: string;
  storage: StoredAsset;
  model?: string;
};

type SceneShape = {
  scene_id: string;
  final_clip?: FinalClip | null;
  video_versions?: SceneAssetVersion[];
  video_active_version_id?: string | null;
  config_overrides?: { model?: string };
};

type ScriptShape = { scenes: SceneShape[] };

function urlOfStorage(storage: StoredAsset): string {
  if (storage.kind === 'fal_passthrough') return storage.url;
  return `supabase://${storage.path}`;
}

export async function generateMasterClipAction(rawInput: unknown): Promise<
  | { ok: true; job_id: string; existing: boolean }
  | { ok: false; error: string }
  | {
      ok: false;
      error: 'tier_gate';
      tier_gate: {
        required_tier: import('@mango/core').AccountTier;
        kind: import('@mango/core').MediaJobKind;
        message: string;
      };
    }
  | {
      ok: false;
      error: 'insufficient_balance';
      insufficient_balance: {
        required_kopeks: number;
        current_kopeks: number;
        kind: import('@mango/core').MediaJobKind;
        model_tier: ModelTier | null;
      };
    }
> {
  let input: Input;
  try {
    input = InputSchema.parse(rawInput);
  } catch {
    return { ok: false, error: 'invalid input' };
  }

  let user: { id: string };
  try {
    user = await getCurrentUser();
  } catch {
    return { ok: false, error: 'unauthorized' };
  }

  const sb = await getServerSupabase();
  const { data: project, error } = await sb
    .from('projects')
    .select('id, user_id, tier, script')
    .eq('id', input.project_id)
    .single();
  if (error || !project) return { ok: false, error: 'project not found' };
  if (project.user_id !== user.id) return { ok: false, error: 'forbidden' };

  const script = project.script as unknown as ScriptShape;
  if (!script) return { ok: false, error: 'project has no script' };

  // Post-2026-05-13 (audio rip-out): every active video model carries
  // native audio inside the clip; ffmpeg merge-videos preserves it through
  // the concat. New scenes have no final_clip — we just use the active
  // video version. Legacy scenes that DO have a final_clip (muxed pre-rip)
  // still take the preferred path so re-runs are idempotent.
  type ResolvedClip = {
    scene_id: string;
    url: string;
    video_version_id: string;
    voice_audio_version_id: string | null;
  };
  const resolved: ResolvedClip[] = [];
  for (const s of script.scenes) {
    if (s.final_clip) {
      resolved.push({
        scene_id: s.scene_id,
        url: urlOfStorage(s.final_clip.storage),
        video_version_id: s.final_clip.composed_from.video_version_id,
        voice_audio_version_id: s.final_clip.composed_from.voice_audio_version_id,
      });
      continue;
    }
    const activeVid =
      s.video_active_version_id && s.video_versions
        ? s.video_versions.find((v) => v.version_id === s.video_active_version_id)
        : null;
    if (activeVid) {
      resolved.push({
        scene_id: s.scene_id,
        url: urlOfStorage(activeVid.storage),
        video_version_id: activeVid.version_id,
        voice_audio_version_id: null,
      });
      continue;
    }
    return {
      ok: false,
      error: `scene ${s.scene_id} has no final_clip and no active video version`,
    };
  }

  const composed = resolved.map((r) => ({
    scene_id: r.scene_id,
    video_version_id: r.video_version_id,
    voice_audio_version_id: r.voice_audio_version_id,
  }));
  const clip_urls = resolved.map((r) => r.url);

  // Post-rip-out: a scene has audio in the master iff (a) it has a legacy
  // muxed final_clip OR (b) its active video version was generated by a
  // model with native-audio support. We check the per-version model field
  // first (recorded at submit time), then fall back to the scene-level
  // override or the project default.
  const has_full_audio = resolved.every((r) => {
    const sceneInScript = script.scenes.find((x) => x.scene_id === r.scene_id);
    if (!sceneInScript) return false;
    if (sceneInScript.final_clip) return true; // legacy muxed clip
    const activeVid = sceneInScript.video_versions?.find(
      (v) => v.version_id === r.video_version_id,
    );
    const modelId = activeVid?.model ?? sceneInScript.config_overrides?.model;
    if (!modelId) return false;
    return getVideoModelMeta(modelId)?.has_native_audio === true;
  });

  // Account-tier capability gate (Phase 1.6).
  try {
    const accountTier = await getAccountTier(sb, user.id);
    assertCapabilityOrLog(accountTier, 'master_clip');
  } catch (err) {
    if (err instanceof TierGateError) {
      return {
        ok: false,
        error: 'tier_gate',
        tier_gate: {
          required_tier: err.required_tier,
          kind: err.kind,
          message: err.message,
        },
      } as const;
    }
    throw err;
  }

  // Phase 1.7 — Balance pre-flight (cheap UX gate; not the atomic authority).
  const balance = await getBalance(sb, user.id);
  const priceKop = priceKopeks('master_clip'); // flat 1000 kopeks, no tier arg
  if (priceKop > 0) {
    try {
      assertBalanceOrLog(balance, 'master_clip');
    } catch (err) {
      if (err instanceof BalanceGateError) {
        return {
          ok: false,
          error: 'insufficient_balance',
          insufficient_balance: {
            required_kopeks: err.required_kopeks,
            current_kopeks: err.current_kopeks,
            kind: err.kind,
            model_tier: null, // master_clip has no tier
          },
        } as const;
      }
      throw err;
    }
  }

  // Provider is resolved after the tier gate so trial users never touch it.
  const provider = getMediaProvider();
  const ctx = { user_id: user.id, project_id: input.project_id, character_id: '' };

  // Atomic quota + reservation. master_clip uses the (project_id, kind) partial
  // unique index — dedup hits when a master concat is already running.
  const reservation = await reserveMediaJob({
    user_id: user.id,
    project_id: input.project_id,
    kind: 'master_clip',
  });
  if (!reservation.ok) return { ok: false, error: reservation.error };
  if (reservation.mode === 'reserved' && reservation.dedup) {
    return { ok: true, job_id: reservation.job_id, existing: true };
  }

  // Phase 1.7 — Atomic balance reservation (race-safe authority).
  // Only runs in 'reserved' mode (bypass has no media_jobs row to link).
  // Generated Supabase types don't know about fn_reserve_balance (added in
  // Phase 1.7 migration); cast through unknown, same pattern as D2.
  if (priceKop > 0 && reservation.mode === 'reserved') {
    const reserveBalanceRpc = sb.rpc as unknown as (
      name: string,
      args: Record<string, unknown>,
    ) => Promise<{ data: boolean | null; error: { message: string } | null }>;
    const reserved = await reserveBalanceRpc('fn_reserve_balance', {
      p_job_id: reservation.job_id,
      p_user_id: user.id,
      p_kopeks: priceKop,
      p_kind: 'master_clip',
      p_model_tier: null, // master_clip has no tier
    });
    if (reserved.error || reserved.data === false) {
      await sb.from('media_jobs').update({ status: 'canceled' }).eq('id', reservation.job_id);
      return {
        ok: false,
        error: 'insufficient_balance',
        insufficient_balance: {
          required_kopeks: priceKop,
          current_kopeks: balance, // stale; UI re-fetches on close
          kind: 'master_clip',
          model_tier: null,
        },
      } as const;
    }
  }

  let handle: Awaited<ReturnType<typeof provider.submitMasterConcat>>;
  try {
    handle = await provider.submitMasterConcat({ clip_urls }, ctx);
  } catch (e) {
    if (reservation.mode === 'reserved') {
      await rollbackMediaJobReservation(reservation.job_id);
    }
    throw e;
  }

  const enrichedRequestInput = {
    ...(handle.request_input ?? {}),
    composed,
    has_full_audio,
  };

  if (reservation.mode === 'reserved') {
    await finalizeMediaJobReservation({
      job_id: reservation.job_id,
      model: handle.model_used,
      fal_request_id: handle.fal_request_id,
      request_input: enrichedRequestInput,
    });
    return { ok: true, job_id: reservation.job_id, existing: false };
  }

  // Bypass mode.
  const { job_id, existing } = await recordPendingJob({
    user_id: user.id,
    project_id: input.project_id,
    kind: 'master_clip',
    model: handle.model_used,
    fal_request_id: handle.fal_request_id,
    request_input: enrichedRequestInput,
  });
  return { ok: true, job_id, existing };
}
