/**
 * Few-shot examples for SCRIPT_SYSTEM_PROMPT — embedded as <example> blocks.
 * Each example is a JSON string that parses cleanly via ScriptGenSchema.
 * They demonstrate the structured cinematography vocabulary the Author should produce.
 *
 * 15s "Утренний кот"  — economy tier, 3 scenes, hook→rising→payoff
 * 60s "Космокот и потерянная звезда" — premium tier, 8 scenes, full arc
 */
export const SCRIPT_EXAMPLES = {
  fifteen_sec: JSON.stringify(
    {
      title: 'Утренний кот',
      tier: 'economy',
      visual_theme: {
        palette: ['#F4E4BC', '#3D2914', '#E8B86D'],
        lighting: 'soft golden-hour key + warm fill + cool rim',
        lens: '85mm shallow DOF',
        motion: 'locked-off + occasional slow dolly',
        mood: 'cozy',
        film_look: 'warm grain 16mm',
        avoid: ['harsh shadows', 'cool blue tones', 'fast cuts'],
      },
      narrator_voice: {
        tts_voice_id: 'EXAVITQu4vr4xnSDxMaL',
        persona:
          'Bright, mid-range female voice — General American — clear neutral timbre — quick tempo with crisp consonants — soprano range with bright top notes — energetic and upbeat baseline — slight vocal fry on declarative endings',
        stability: 0.65,
        similarity_boost: 0.75,
        style: 0.1,
        speed: 0.9,
      },
      characters: [
        {
          action: 'add',
          name: 'Барсик',
          description:
            'Рыжий полосатый кот, пушистый, с большими янтарными глазами. Лениво-грациозный, обожает солнечные пятна на полу.',
          appearance: {
            species: 'кот',
            age: 'взрослый',
            build: 'пухленький, пушистый',
            distinctive: ['рыжие полосы', 'янтарные глаза', 'белые лапки'],
          },
          personality: 'Флегматичный философ. Жизнь хороша, пока есть солнечный луч и миска.',
        },
      ],
      scenes: [
        {
          scene_id: 'scene-01',
          description: 'Рыжий кот просыпается в солнечном луче на подоконнике.',
          description_ru:
            'Утренний луч золотым мечом прорезает занавеску и ложится прямо на рыжий бок дремлющего Барсика. Кот медленно щурится, вытягивает переднюю лапу и снова замирает.',
          description_en:
            'A golden morning beam cuts through the curtain and falls on the sleeping ginger cat. Barsik slowly squints, stretches one paw forward, and goes still again.',
          duration_sec: 5,
          dialogue: { speaker: 'narrator', text: 'Утро начинается с самого важного.' },
          character_ids: ['Барсик'],
          composition: {
            shot_size: 'close_up',
            angle: 'eye_level',
            framing_notes: 'Кот в центре, солнечный луч диагональю слева сверху.',
            subject_focus: 'Барсик на подоконнике',
          },
          camera_movement: {
            kind: 'dolly_in',
            speed: 'slow',
            lens_character: '85mm f/1.8 боке на занавеске',
          },
          lighting: {
            recipe: 'soft golden-hour key + warm fill',
            time_of_day: 'раннее утро',
            key_direction: 'слева через окно',
          },
          audio_direction: {
            ambient: 'тихое чириканье воробьёв за окном',
            music: 'нежное пианино C-мажор, pianissimo',
            sfx: ['потягивание кота'],
            voice_notes: 'нарратор говорит тихо, с улыбкой',
          },
          arc_role: 'hook',
          tier_at_gen: 'economy',
          audio_mode: 'auto',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-02',
          description: 'Барсик обходит кухню, обнюхивает пустую миску.',
          description_ru:
            'Барсик спрыгивает с подоконника мягко, без звука, и величественно шествует на кухню. Наклоняется к миске — та пуста. Кот смотрит в камеру с немым укором.',
          description_en:
            'Barsik drops silently from the windowsill and pads regally to the kitchen. He leans toward the bowl — empty. The cat looks into the camera with wordless reproach.',
          duration_sec: 5,
          dialogue: {
            speaker: 'narrator',
            text: 'Первая проверка дня: а вдруг еда сама появилась?',
          },
          character_ids: ['Барсик'],
          composition: {
            shot_size: 'medium',
            angle: 'low_angle',
            framing_notes: 'Угол снизу — кот выглядит монументально над пустой миской.',
            subject_focus: 'Барсик и миска',
          },
          camera_movement: {
            kind: 'static',
            speed: 'slow',
            lens_character: '85mm, лёгкое боке на фоне кухни',
          },
          lighting: {
            recipe: 'warm fill + cool rim',
            time_of_day: 'утро',
            key_direction: 'справа из окна кухни',
          },
          audio_direction: {
            ambient: 'тиканье старых часов на стене',
            music: 'пианино замирает на паузе',
            sfx: ['мягкие шаги по паркету', 'звон пустой миски'],
            voice_notes: 'нарратор с лёгкой иронией',
          },
          arc_role: 'rising',
          tier_at_gen: 'economy',
          audio_mode: 'auto',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-03',
          description: 'Барсик возвращается на подоконник, щурится на солнце — доволен.',
          description_ru:
            'Убедившись, что еда не появилась волшебным образом, Барсик возвращается к подоконнику, сворачивается клубком прямо в солнечном пятне и жмурится. Завтрак подождёт.',
          description_en:
            'Satisfied that food did not appear by magic, Barsik returns to the windowsill, curls up in the sunspot, and squints contentedly. Breakfast can wait.',
          duration_sec: 5,
          dialogue: { speaker: 'narrator', text: 'Солнце никуда не делось. День удался.' },
          character_ids: ['Барсик'],
          composition: {
            shot_size: 'medium_close_up',
            angle: 'eye_level',
            framing_notes: 'Кот в клубке, за ним — размытый силуэт города в окне.',
            subject_focus: 'Барсик, свернувшийся в клубок',
          },
          camera_movement: {
            kind: 'dolly_out',
            speed: 'slow',
            lens_character: '85mm, тёплая виньетка по краям',
          },
          lighting: {
            recipe: 'soft golden-hour key + warm fill',
            time_of_day: 'утро, чуть позже',
            key_direction: 'слева, чуть ярче чем в первой сцене',
          },
          audio_direction: {
            ambient: 'далёкий городской гул, птицы',
            music: 'пианино возвращается, тема чуть полнее, финальный аккорд',
            sfx: ['мурлыканье'],
            voice_notes: 'нарратор тепло, с финальной точкой',
          },
          arc_role: 'payoff',
          tier_at_gen: 'economy',
          audio_mode: 'auto',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
      ],
      master_clip_versions: [],
      master_clip_active_version_id: null,
    },
    null,
    2,
  ),

  sixty_sec: JSON.stringify(
    {
      title: 'Космокот и потерянная звезда',
      tier: 'premium',
      visual_theme: {
        palette: ['#0A1628', '#3D5B7A', '#8A6FD8', '#E4B863'],
        lighting: 'rim-heavy with bioluminescent fills',
        lens: 'anamorphic 40mm',
        motion: 'floating handheld + crane reveals',
        mood: 'wondrous',
        film_look: 'anamorphic lens flares, deep blacks, teal-violet grade',
        avoid: ['warm yellows as dominants', 'locked-off static shots', 'flat lighting'],
      },
      narrator_voice: {
        tts_voice_id: 'pNInz6obpgDQGcFmaJgB',
        persona:
          'Soft, mid-range female voice — General American — slightly breathy timbre — medium tempo with thoughtful pauses — mid-tenor pitch with warm range — calm and curious baseline — drags out vowels on key words',
        stability: 0.7,
        similarity_boost: 0.8,
        style: 0.15,
        speed: 0.85,
      },
      characters: [
        {
          action: 'add',
          name: 'Космокот',
          description:
            'Тёмно-синий кот с мерцающими звёздами в шерсти, большими фиолетовыми глазами. Носит маленький скафандр с открытым шлемом. Смелый, любопытный, немного растерянный.',
          appearance: {
            species: 'кот',
            age: 'молодой взрослый',
            build: 'стройный, грациозный',
            distinctive: [
              'звёзды в шерсти',
              'фиолетовые глаза',
              'скафандр с открытым шлемом',
              'светящийся хвост',
            ],
          },
          personality:
            'Бесстрашный исследователь с мягким сердцем. Никогда не оставит друга в беде.',
        },
        {
          action: 'add',
          name: 'Искра',
          description:
            'Маленький дух потерянной звезды — светящийся шарик золотистого света с тонкими лучиками-ручками. Пугливая, одинокая, но искренняя.',
          appearance: {
            species: 'звёздный дух',
            age: 'юный',
            build: 'крошечный, невесомый',
            distinctive: ['золотистое свечение', 'тонкие лучи вместо рук', 'мерцает когда рада'],
          },
          personality: 'Робкая, но любопытная. Тоскует по своему созвездию.',
        },
      ],
      scenes: [
        {
          scene_id: 'scene-01',
          description: 'Космокот летит сквозь звёздное поле на маленьком ракетном самокате.',
          description_ru:
            'Чёрный бархат космоса. Тысячи звёзд плывут мимо в нежном мерцании. Космокот мчится на крошечном ракетном самокате, его шерсть переливается — каждая звезда в ней отражает настоящее небо.',
          description_en:
            'Black velvet of space. Thousands of stars drift past in gentle shimmer. Cosmocat zooms on a tiny rocket scooter, his fur shimmering — each star in it mirrors the real sky.',
          duration_sec: 7,
          dialogue: {
            speaker: 'narrator',
            text: 'На краю Галактики Мурлыканья есть один очень занятой кот.',
          },
          character_ids: ['Космокот'],
          composition: {
            shot_size: 'wide',
            angle: 'low_angle',
            framing_notes:
              'Кот снизу в перспективе, звёздное поле уходит вглубь, ракетный выхлоп оставляет золотой след.',
            subject_focus: 'Космокот на самокате',
          },
          camera_movement: {
            kind: 'tracking',
            speed: 'medium',
            lens_character: 'anamorphic 40mm, горизонтальные блики',
          },
          lighting: {
            recipe: 'deep cosmic rim + starfield ambient',
            time_of_day: 'открытый космос',
            key_direction: 'слева, холодный синий',
          },
          audio_direction: {
            ambient: 'глубокий гул космоса, низкий дрон',
            music: 'оркестр нарастает, тема приключения',
            sfx: ['гудение ракетного двигателя', 'свист сквозь пространство'],
            voice_notes: 'нарратор торжественно, с широкой улыбкой',
          },
          arc_role: 'hook',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-02',
          description: 'Космокот замечает странное тусклое пятно там, где должна быть звезда.',
          description_ru:
            'Вдруг самокат резко тормозит. Космокот принюхивается. Там, где на его звёздной карте отмечена яркая точка — темно. Пусто. Только лёгкое золотистое мерцание на краю темноты.',
          description_en:
            'The scooter brakes sharply. Cosmocat sniffs the air. Where his star map marks a bright dot — darkness. Empty. Only a faint golden shimmer at the edge of the void.',
          duration_sec: 8,
          dialogue: {
            speaker: 'narrator',
            text: 'Но сегодня что-то было не так с созвездием Рыбьего Хвоста.',
          },
          character_ids: ['Космокот'],
          composition: {
            shot_size: 'medium_close_up',
            angle: 'eye_level',
            framing_notes: 'Кот смотрит вдаль, за ним тёмное пятно в звёздном поле.',
            subject_focus: 'взгляд Космокота вдаль',
          },
          camera_movement: {
            kind: 'handheld',
            speed: 'slow',
            lens_character: 'anamorphic 40mm, чуть расфокус на краях',
          },
          lighting: {
            recipe: 'starfield ambient + missing-star void shadow',
            time_of_day: 'открытый космос',
            key_direction: 'слева тусклый, справа темнота',
          },
          audio_direction: {
            ambient: 'гул стихает, тишина',
            music: 'оркестр умолкает, одинокая флейта',
            sfx: ['скрип тормозов самоката'],
            voice_notes: 'пауза после реплики нарратора',
          },
          arc_role: 'setup',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-03',
          description: 'Космокот находит Искру — крошечный дух потерянной звезды.',
          description_ru:
            'Из темноты выплывает крошечный светящийся шарик — Искра. Она жмётся к астероиду, дрожит, почти не светится. Космокот осторожно протягивает лапу.',
          description_en:
            'From the darkness drifts a tiny glowing orb — Iskra. She huddles against an asteroid, trembling, barely luminous. Cosmocat gently extends a paw.',
          duration_sec: 8,
          dialogue: { speaker: 'Космокот', text: 'Эй... ты не потерялась?' },
          character_ids: ['Космокот', 'Искра'],
          composition: {
            shot_size: 'medium',
            angle: 'eye_level',
            framing_notes: 'Двое в кадре: кот справа крупнее, Искра слева меньше и тусклее.',
            subject_focus: 'встреча Космокота и Искры',
          },
          camera_movement: {
            kind: 'dolly_in',
            speed: 'slow',
            lens_character: 'anamorphic 40mm, мягкое боке на астероиде',
          },
          lighting: {
            recipe: 'bioluminescent fill from Iskra + cold star rim',
            time_of_day: 'открытый космос',
            key_direction: 'Искра как точечный источник слева',
          },
          audio_direction: {
            ambient: 'тишина пронизывает кадр',
            music: 'флейта превращается в нежную тему знакомства',
            sfx: ['лёгкое мерцание Искры'],
            voice_notes: 'Космокот говорит тихо, бережно',
          },
          arc_role: 'setup',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-04',
          description: 'Искра рассказывает: её сдул Большой Звёздный Ветер.',
          description_ru:
            'Искра мерцает, пытаясь объяснить. Её лучики-ручки показывают направление — туда, откуда дул страшный ветер. Кот слушает серьёзно, уши прижаты вперёд.',
          description_en:
            'Iskra flickers, trying to explain. Her ray-arms point in a direction — toward where the terrible wind blew from. The cat listens seriously, ears pricked forward.',
          duration_sec: 7,
          dialogue: { speaker: 'Искра', text: 'Большой Ветер... он меня унёс...' },
          character_ids: ['Космокот', 'Искра'],
          composition: {
            shot_size: 'close_up',
            angle: 'low_angle',
            framing_notes: 'Искра в центре, снизу — выглядит уязвимо, Космокот слушает за кадром.',
            subject_focus: 'Искра рассказывает',
          },
          camera_movement: {
            kind: 'handheld',
            speed: 'slow',
            lens_character: 'anamorphic 40mm, лёгкое дыхание камеры',
          },
          lighting: {
            recipe: 'Iskra glow as key, deep space fill',
            time_of_day: 'открытый космос',
            key_direction: 'Искра центр кадра как источник',
          },
          audio_direction: {
            ambient: 'далёкий звук ветра в пространстве',
            music: 'тихий струнный орнамент',
            sfx: ['мерцание Искры', 'отзвук ветра'],
            voice_notes: 'Искра говорит тихо, дрожащим голосом',
          },
          arc_role: 'rising',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-05',
          description: 'Космокот решает помочь. Они летят к созвездию Рыбьего Хвоста.',
          description_ru:
            'Космокот берёт Искру под лапу — бережно, как берут хрустальный шар — и они мчатся на самокате сквозь метеоритный дождь к далёкому созвездию. Искра начинает светиться чуть ярче.',
          description_en:
            'Cosmocat tucks Iskra under his paw — gently, like cradling a crystal ball — and they zoom through a meteor shower toward the distant constellation. Iskra begins to glow a little brighter.',
          duration_sec: 8,
          dialogue: { speaker: 'Космокот', text: 'Я знаю дорогу. Держись крепче!' },
          character_ids: ['Космокот', 'Искра'],
          composition: {
            shot_size: 'wide',
            angle: 'low_angle',
            framing_notes:
              'Широкий план: самокат в правой трети, созвездие вдалеке слева, метеориты в движении.',
            subject_focus: 'путешествие Космокота и Искры',
          },
          camera_movement: {
            kind: 'tracking',
            speed: 'fast',
            lens_character: 'anamorphic 40mm, горизонтальные смазы на метеоритах',
          },
          lighting: {
            recipe: 'star-trail rim + Iskra warm key + meteor flash fills',
            time_of_day: 'открытый космос',
            key_direction: 'смешанный, динамичный',
          },
          audio_direction: {
            ambient: 'свист метеоритного дождя',
            music: 'тема приключения возвращается, нарастает',
            sfx: ['гул двигателя на максимуме', 'удары метеоритов рядом'],
            voice_notes: 'Космокот говорит с воодушевлением',
          },
          arc_role: 'rising',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-06',
          description:
            'Путь блокирует Тёмный Вихрь — космический шторм, закрывший вход в созвездие.',
          description_ru:
            'Перед ними — чёрная воронка Тёмного Вихря. Искра гаснет от страха. Самокат трясёт. Космокот встаёт на его корму и смотрит в пасть шторма — его звёзды в шерсти пылают ярко.',
          description_en:
            "Before them — the black funnel of the Dark Vortex. Iskra goes dark with fear. The scooter shakes. Cosmocat stands on its back end and stares into the storm's maw — the stars in his fur blaze bright.",
          duration_sec: 8,
          dialogue: {
            speaker: 'narrator',
            text: 'Но путь домой преграждал Тёмный Вихрь — и он был огромен.',
          },
          character_ids: ['Космокот', 'Искра'],
          composition: {
            shot_size: 'extreme_wide',
            angle: 'low_angle',
            framing_notes:
              'Вихрь занимает 70% кадра сверху, самокат крошечный внизу по центру, контраст масштаба.',
            subject_focus: 'Тёмный Вихрь против Космокота',
          },
          camera_movement: {
            kind: 'crane_up',
            speed: 'slow',
            lens_character: 'anamorphic 40mm, вертикальный reveal вихря',
          },
          lighting: {
            recipe: 'void dark key + lightning flash fills + Cosmocat star-glow counter-rim',
            time_of_day: 'открытый космос',
            key_direction: 'тёмный верх, свет снизу от кота',
          },
          audio_direction: {
            ambient: 'инфразвук вихря, давящий',
            music: 'оркестр — тема опасности, медь и ударные',
            sfx: ['рёв вихря', 'вибрация самоката', 'потрескивание молний'],
            voice_notes: 'нарратор весомо, пауза после слова "огромен"',
          },
          arc_role: 'climax',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-07',
          description: 'Космокот направляет свет Искры в сердце вихря — шторм рассеивается.',
          description_ru:
            'Космокот поднимает Искру вверх, держа её на вытянутых лапах. Искра понимает — и вспыхивает. Золотой луч пронзает воронку. Вихрь кричит, дрожит и рассыпается в серебряную пыль. Впереди — открытое созвездие.',
          description_en:
            'Cosmocat lifts Iskra up high, holding her on outstretched paws. Iskra understands — and blazes. A golden beam pierces the funnel. The vortex screams, shudders, and dissolves into silver dust. Ahead — the open constellation.',
          duration_sec: 7,
          dialogue: { speaker: 'Искра', text: 'Я... я помню, кто я!' },
          character_ids: ['Космокот', 'Искра'],
          composition: {
            shot_size: 'medium',
            angle: 'low_angle',
            framing_notes:
              'Кот держит Искру над головой, золотой луч уходит в кадр вверх, вихрь рассыпается по краям.',
            subject_focus: 'Искра вспыхивает, разгоняя вихрь',
          },
          camera_movement: {
            kind: 'crane_up',
            speed: 'medium',
            lens_character: 'anamorphic 40mm, лёгкая засветка от Искры',
          },
          lighting: {
            recipe: 'Iskra blast key — warm gold, vortex dissolution fills — silver flash',
            time_of_day: 'открытый космос',
            key_direction: 'Искра сверху центр как точечный взрыв',
          },
          audio_direction: {
            ambient: 'вихрь стихает, после — тишина',
            music: 'оркестр взрыв → тихий мажорный хор',
            sfx: ['вспышка Искры', 'рёв вихря затихает', 'звон рассыпающихся частиц'],
            voice_notes: 'Искра — с удивлением и радостью',
          },
          arc_role: 'payoff',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
        {
          scene_id: 'scene-08',
          description: 'Искра возвращается в созвездие. Космокот машет лапой и летит дальше.',
          description_ru:
            'Искра занимает своё место в созвездии Рыбьего Хвоста — оно вспыхивает полным светом. Космокот смотрит на неё, улыбается (ухо вверх, хвост дугой), потом разворачивает самокат и снова уносится в глубину звёздного поля.',
          description_en:
            'Iskra takes her place in the Fish-Tail constellation — it blazes back to full brightness. Cosmocat watches her, smiles (ear up, tail arched), then turns his scooter and rockets back into the depths of the star field.',
          duration_sec: 7,
          dialogue: {
            speaker: 'narrator',
            text: 'Так Космокот вернул звезду домой. А потом полетел туда, где ждала следующая история.',
          },
          character_ids: ['Космокот', 'Искра'],
          composition: {
            shot_size: 'wide',
            angle: 'high_angle',
            framing_notes:
              'Созвездие сверху полным светом, самокат внизу удаляется в глубину кадра.',
            subject_focus: 'возвращение Искры домой + уход Космокота',
          },
          camera_movement: {
            kind: 'crane_down',
            speed: 'slow',
            lens_character: 'anamorphic 40mm, финальные блики на созвездии',
          },
          lighting: {
            recipe: 'constellation full-bright key + deep space ambient',
            time_of_day: 'открытый космос',
            key_direction: 'сверху — свет созвездия',
          },
          audio_direction: {
            ambient: 'мягкий космический хор',
            music: 'полная оркестровая тема, победная, затем плавно стихает',
            sfx: ['мурлыканье Космокота вдалеке', 'звон созвездия'],
            voice_notes: 'нарратор с тёплой финальной интонацией',
          },
          arc_role: 'cta',
          tier_at_gen: 'premium',
          audio_mode: 'native',
          first_frame_source: 'auto_continuity',
          first_frame_versions: [],
          first_frame_active_version_id: null,
          video_versions: [],
          video_active_version_id: null,
          voice_audio_versions: [],
          voice_audio_active_version_id: null,
          last_frame: null,
          final_clip: null,
        },
      ],
      master_clip_versions: [],
      master_clip_active_version_id: null,
    },
    null,
    2,
  ),
};
