-- 2026-05-22 — HISTORICAL NOTE.
--
-- The ORIGINAL content of this migration granted EXECUTE on `fn_reserve_balance`
-- and `fn_settle_paid_intent` to `authenticated, anon` in an attempt to fix a
-- "permission denied for function fn_reserve_balance" error reported in prod.
--
-- That grant was a LIVE SECURITY HOLE: both functions are SECURITY DEFINER
-- and trust caller-supplied `p_user_id` without any auth.uid() check, so any
-- authenticated user could call the RPC directly and debit/refund ANY user's
-- balance by passing someone else's UUID. Caught by Codex post-merge audit
-- the same day; revoked via Supabase MCP within ~30 minutes of being granted.
--
-- The REAL fix is `20260522000004_revoke_unsafe_user_session_grants.sql`
-- (which REVOKEs the grants from this file). Server actions now call these
-- functions via the service_role client — the user-session client never
-- reaches the function, so the SECURITY DEFINER's trust of `p_user_id` is
-- only ever invoked with a value the server itself just read from
-- authenticated cookies.
--
-- This file is left in place (as a no-op grant-then-revoke would be confusing
-- and the revoke migration is the operational source of truth) but its body
-- is replaced with a comment so re-applying the migration set on a fresh
-- database does NOT recreate the hole. The revoke migration runs
-- immediately after this one in lexical order regardless.
--
-- See:
--   - 20260522000004_revoke_unsafe_user_session_grants.sql — the corrective REVOKE
--   - apps/web/src/server/actions/generateSceneVideoAction.ts (service_role swap)
--   - apps/web/src/server/actions/generateMasterClipAction.ts (same)
--   - Codex audit log on PR #53 (BLOCKER #1)

-- (Intentionally empty: see the historical note above.)
SELECT 1;
